#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd -m -1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a spad_calc sticky=on state=floating rectangle=350x400+1250+250
bspc rule -a scpad sticky=on state=floating rectangle=800x500+1000+250

# Border
bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#292e42"
bspc config active_border_color "#292e42"

xsetroot -cursor_name left_ptr

polybar top &
picom &
